const ansiDeviceStatusReportCursorPosition = '\x1b[6n';
const ansiEraseInLineRight = '\x1b[K';
const ansiEraseInDisplayAll = '\x1b[2J';
const ansiHideCursor = '\x1b[?25l';
const ansiShowCursor = '\x1b[?25h';
const ansiCursorLeft = '\x1b[D';
const ansiCursorRight = '\x1b[C';
const ansiCursorUp = '\x1b[A';
const ansiCursorDown = '\x1b[B';
const ansiResetCursorPosition = '\x1b[H';
const ansiMoveCursorToScreenEdge = '\x1b[999C\x1b[999B';
String ansiCursorPosition({int row = 1, int col = 1}) => '\x1b[${row};${col}H';
